name: Module Test Harness

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@a26d1abb482f8615f50f54e3e5ca2b9ed0e349d4
    with:
      provider: digitalocean
      working_directory: ./_examples/basic/

  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@a26d1abb482f8615f50f54e3e5ca2b9ed0e349d4
    with:
      provider: digitalocean
      working_directory: ./_examples/complete/
