name: Tag Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    uses: clouddrove/github-shared-workflows/.github/workflows/tag-release.yml@2.1.0
    with:
      target_branch: master
    secrets:
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
