name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@2.1.0 # pinned to latest
    with:
      provider: none
      working_directory: './_examples/basic/'
      provider: none
  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@2.1.0 # pinned to latest
    with:
      provider: none
      working_directory: './_examples/complete/'
      provider: none

# Separate job for TFlint workflow call
  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-lint.yml@2.1.1 # pinned to latest
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
